services:
  udp-message-generator:
    build:
      context: ./udp-message-generator
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - udp-server

  udp-server:
    build:
      context: ./udp-server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  ui:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - api
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telemetry
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
